name: Build libctru

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    container:
      image: 'devkitpro/devkitarm'

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: build
        run: make -C libctru
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: |
            libctru/lib/libctru.a
